### ISSUE TITLE
removing models dynamically

### ISSUE THREAD

**Issue by moviek** [beaston02/ChaturbateRecorder#17]
First of all, thanks for all the hardwork on getting this working. 

For the camsoda script, removing models from wanted.txt works, but not for the ChaturbateRecorder.

Python will call it every 20 seconds, if you remove the name, the name still is in the file.
Having this ability will help if you want to stop recording the model  cleanly instead of via control-C

**Comment by beaston02** [comment]
Thank you! 

By stop recording do you mean end the current recording right then and there? If so, I don't think (but I many be wrong) that any of the scripts function this way. It should finish that recording and then not start a new one after that. The one exception would be in my MFC script which would stop if the model was added to the blacklist. 

I could add the functionality to stop a model when they are removed from the wanted list, which I think is what you're looking for, I just wanted to make sure I'm not misunderstanding.

**Comment by moviek** [comment]
Yep. That's the functionality. Basically stop a model when they are removed
from the list. Other than that, everything is tested and working.

I wonder what the limit is for the # of models is on Chaturbate. You had
like 50 in your wanted list? or more near to 10?

**Comment by beaston02** [comment]
I just changed it so they will be removed when the next check for online models is done (thats when the file is read so thats when the script will see they were removed).

as far as how many models can record at once will completely depend on your system. There is no hard limit, but obviously your system needs to have the ability to write to the disk fast enough, and enough bandwidth to handle all of the data. The most Ive personally been able to record at once on one system was around 500 - 600 models. That was on a dedicated server with a 1Gbps line, but I ultimately found it was better to distribute the jobs among several smaller VPSs each doing about 50 - 60 recordings max at one time.

**Comment by moviek** [comment]
Nah man I was talking about when they would ban your IP for that many
streams! I don't have enough HDD for that many models!

Thanks for the fix. Will QA and report back results.

**Comment by beaston02** [comment]
lol, well Ive never found a point where they blocked any of my IP addresses, and I had several hundred going at a time before, so I dont believe they monitor the IP addresses too closely, if at all. 

Let me know how it works for you.

**Comment by moviek** [comment]
Seems ok! Will let you know if I encounter any issues . Thanks again man!

**Comment by r00tedu** [comment]
This broke mine on an Ubuntu host running python3.5 and also a freenas 11  running python3.6.

```
[2017-09-25 23:52:46] 7 model(s) are being recorded. Next check in 20 seconds
Exception in thread Thread-105:recorded: ['xxxxxx', 'yyyyyy', 'zzzzzzzz']
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "ChaturbateRecorder.py", line 38, in startRecording
    streams = session.streams("hlsvariant://{}".format(result['hls_source'].rsplit('?')[0]))
KeyError: 'hls_source'
[2017-09-25 23:53:16] 1 model(s) are being recorded. Next check in 18 seconds
Exception in thread Thread-119:recorded: ['xxxxxxx']
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "ChaturbateRecorder.py", line 38, in startRecording
    streams = session.streams("hlsvariant://{}".format(result['hls_source'].rsplit('?')[0]))
KeyError: 'hls_source'
[2017-09-25 23:53:42] 7 model(s) are being recorded. Next check in 20 seconds
Exception in thread Thread-143:recorded: ['yyyyyy', 'xxxxxx', 'zzzzzzzz']
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "ChaturbateRecorder.py", line 38, in startRecording
    streams = session.streams("hlsvariant://{}".format(result['hls_source'].rsplit('?')[0]))
KeyError: 'hls_source'
[2017-09-25 23:54:09] 2 model(s) are being recorded. Next check in 20 seconds
Exception in thread Thread-157:recorded:['yyyyyy', 'xxxxxx', 'zzzzzzzz']
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "ChaturbateRecorder.py", line 38, in startRecording
    streams = session.streams("hlsvariant://{}".format(result['hls_source'].rsplit('?')[0]))
KeyError: 'hls_source'
[2017-09-25 23:54:29] 7 model(s) are being recorded. Getting list of online models now
^CTraceback (most recent call last):ded: ['yyyyyy', 'xxxxxx', 'zzzzzzzz']

```

**Comment by moviek** [comment]
I didn't try on 3.6. Let me test it with more models. I only with 2 for a
little bit. More testing in progress.

**Comment by r00tedu** [comment]
Everything works but it keeps creating new files / restarting streams after every pull.

**Comment by beaston02** [comment]
Thank you for letting me know, r00tedu. I only tested on my Mac rubbing python3.5. I will test it on my Ubuntu server also and see if I can figure out what's causing it. 

Which version of Ubuntu are you running? 

I have a busy day today, so I'm not sure if I'll get to it today or not, but I'll keep you updated here.

**Comment by r00tedu** [comment]
Actually my VM was debian 9. I just tested on a fresh Ubuntu 16.04 VM with python3.5 and am getting similar results just no console errors. It is however creating new mp4 files after every model check. 

The new VM is a 16.04 ubuntu VM with apt-get upgrade ran, and then apt-get install python3-pip and then I ran python3.5 -m pip install livestreamer bs4 lxml gevent.

**Comment by beaston02** [comment]
@r00tedu, It should be working now. I tested on Ubuntu 16.04 and it is working well on my end. 

Let me know if this fixed the issue for you

**Comment by r00tedu** [comment]
That resolved the issue. Thank you!

**Comment by moviek** [comment]
I updated to the latest and found this though repeated every 20 sec:
I haven't changed my wanted.txt file either and this was with the latest
pull, python3.5 on mac OS X Yosemite

---

[2017-09-27 18:20:59] 0 model(s) are being recorded. Next check in 20
seconds
Exception in thread Thread-129:recorded: []
Traceback (most recent call last):
  File
"/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py",
line 914, in _bootstrap_inner
    self.run()
  File
"/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py",
line 862, in run
    self._target(*self._args, **self._kwargs)
  File "ChaturbateRecorder.py", line 38, in startRecording
    streams =
session.streams("hlsvariant://{}".format(result['hls_source'].rsplit('?')[0]))
  File
"/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/livestreamer/session.py",
line 355, in streams
    return plugin.streams(**params)
  File
"/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/livestreamer/plugin/plugin.py",
line 227, in streams
    ostreams = self._get_streams()
  File
"/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/livestreamer/plugins/stream.py",
line 54, in _get_streams
    urlnoproto = re.match("^\w+://(.+)", url).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by beaston02** [comment]
@moviek, I changed the error handling, so it's logging more to the console. Before that would have just eroded out in the background. models who are online and in free chat should record still, just the same as they were before. I'll fix it to clean up the output, but other than the messy output it should work fine. I'm replying from my phone, which makes it a bit more difficult to read than it would be on the computer so it's possible it's possible I'm overlooking something. I'll read over it all again when I get a chance to sit down at my computer, and I'll fix it to clean up the output then also.

**Comment by moviek** [comment]
oh yeah no rush, but you're right it works :) thanks again.
