### ISSUE TITLE
error interrupts recording

### ISSUE THREAD

**Issue by orchid666** [beaston02/ChaturbateRecorder#20]
Hello, sometimes I get this error after the "Next check". I think it is happening when a streamer goes on a private session, but not sure.

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "ChaturbateRecorder.py", line 38, in startRecording
    streams = session.streams("hlsvariant://{}".format(result['hls_source'].rsplit('?')[0]))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/livestreamer/session.py", line 355, in streams
    return plugin.streams(**params)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/livestreamer/plugin/plugin.py", line 227, in streams
    ostreams = self._get_streams()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/livestreamer/plugins/stream.py", line 54, in _get_streams
    urlnoproto = re.match("^\w+://(.+)", url).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

Exception in thread Thread-43:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "ChaturbateRecorder.py", line 38, in startRecording
    streams = session.streams("hlsvariant://{}".format(result['hls_source'].rsplit('?')[0]))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/livestreamer/session.py", line 355, in streams
    return plugin.streams(**params)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/livestreamer/plugin/plugin.py", line 227, in streams
    ostreams = self._get_streams()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/livestreamer/plugins/stream.py", line 54, in _get_streams
    urlnoproto = re.match("^\w+://(.+)", url).group(1)

**Comment by RonnieBlaze** [comment]
getting the same problem here.. and ive noticed that after awhile the script seems to crash

**Comment by beaston02** [comment]
I just posted an update. Unfortunately I havent been able to determine the cause of this. As far as I can tell, it is not in the script itself, but something on the sites end. It seems to be uncommon enough that I havent been able to really look into it much (lack of time to sit at the computer and wait for it to happen and find what was going on at that moment on the site to cause it). 

The script should now silence the error instead of logging it to the screen. Thats the best solution I currently have.

**Comment by orchid666** [comment]
Thanks a lot for that, I wish I knew enough Python to be able to help :)
As I mentioned, I think it happens when a cam goes on a private show which cut the video flux but the channel is not technically off.  Dont know if livestreamer handles that.

**Comment by beaston02** [comment]
Im thinking it is something along those lines, although I believe it happens if it tries to start a recording, and the model starts a private/group, or goes offline between the time the script sees them online, and the recording starting (probably a few second window there, maybe more, Ive never timed it). It may be the site is reporting the model as online and in a free chat when they arent actually in a free chat also. As far as I can tell, it isnt actually stopping a recording from happening since I believe it to be occurring when a recording wouldnt be able to start anyways (offline/paid show the script cant access...)


Also, Sorry for the terribly slow reply on this issue. Life has been crazy here, and I had decided to step away from the scripts for a few weeks until things calmed down. I didnt even open the email notifications for the issues as they came in. Im glad nothing broke too bad while I was away!
