### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by NandoPrates** [beaston02/ChaturbateRecorder#21]
Exception in thread Thread-33:_16']
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "ChaturbateRecorder.py", line 38, in startRecording
    streams = session.streams("hlsvariant://{}".format(result['hls_source'].rsplit('?')[0]))
  File "/usr/local/lib/python3.5/site-packages/livestreamer/session.py", line 355, in streams
    return plugin.streams(**params)
  File "/usr/local/lib/python3.5/site-packages/livestreamer/plugin/plugin.py", line 227, in streams
    ostreams = self._get_streams()
  File "/usr/local/lib/python3.5/site-packages/livestreamer/plugins/stream.py", line 54, in _get_streams
    urlnoproto = re.match("^\w+://(.+)", url).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by Zer0t3ch** [comment]
Looks like an issue in the library. IE nothing that the dev can directly fix without forking it. I'm experiencing it as well, but it doesn't seem to cause an issues. Is there some way we could at least silence this call to the library or something? My Python experience is basic and rusty as hell.

**Comment by beaston02** [comment]
This is the same as issue #20 . I just posted an update for the script, and more info can be found in my post on that issue. Im going to close this, and please feel free to continue the discussion there if you have anymore info. 

Thank you!
