### ISSUE TITLE
No Models found

### ISSUE THREAD

**Issue by DeathxBouns** [beaston02/ChaturbateRecorder#32]
On the latest update I cant find any models. When I try an older version I get this error 

python3.6 ChaturbateRecorder.py
[2017-11-24 09:17:17] 0 model(s) are being recorded. Getting list of online mode[2017-11-24 09:17:26] 0 model(s) are being recorded. Next check in 357 seconds
Exception in thread Thread-1:g recorded: []
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/livestreamer/plugin/api/http_session.py", line 130, in request
    res.raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://edge101.stream.highwebmedia.com/live-edge/amlst:sophydiva-sd-7aa9860a7076c61938a2903a5b037f88b221b2629776cdfa23dd41e3afa578ce_trns_h264/playlist.m3u8

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/livestreamer/plugins/stream.py", line 73, in _get_streams
    streams = cls(self.session, urlnoproto, **params)
  File "/usr/local/lib/python3.6/site-packages/livestreamer/stream/hls.py", line 279, in parse_variant_playlist
    res = session_.http.get(url, exception=IOError, **request_params)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/livestreamer/plugin/api/http_session.py", line 135, in request
    raise err
OSError: Unable to open URL: https://edge101.stream.highwebmedia.com/live-edge/amlst:sophydiva-sd-7aa9860a7076c61938a2903a5b037f88b221b2629776cdfa23dd41e3afa578ce_trns_h264/playlist.m3u8 (403 Client Error: Forbidden for url: https://edge101.stream.highwebmedia.com/live-edge/amlst:sophydiva-sd-7aa9860a7076c61938a2903a5b037f88b221b2629776cdfa23dd41e3afa578ce_trns_h264/playlist.m3u8)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "ChaturbateRecorder.py", line 38, in startRecording
    streams = session.streams("hlsvariant://{}".format(result['hls_source'].rsplit('?')[0]))
  File "/usr/local/lib/python3.6/site-packages/livestreamer/session.py", line 355, in streams
    return plugin.streams(**params)
  File "/usr/local/lib/python3.6/site-packages/livestreamer/plugin/plugin.py", line 227, in streams
    ostreams = self._get_streams()
  File "/usr/local/lib/python3.6/site-packages/livestreamer/plugins/stream.py", line 75, in _get_streams
    raise PluginError(err)
livestreamer.exceptions.PluginError: Unable to open URL: https://edge101.stream.highwebmedia.com/live-edge/amlst:sophydiva-sd-7aa9860a7076c61938a2903a5b037f88b221b2629776cdfa23dd41e3afa578ce_trns_h264/playlist.m3u8 (403 Client Error: Forbidden for url: https://edge101.stream.highwebmedia.com/live-edge/amlst:sophydiva-sd-7aa9860a7076c61938a2903a5b037f88b221b2629776cdfa23dd41e3afa578ce_trns_h264/playlist.m3u8)

OS: Raspbian 
Python: 3.6 

I can't find models on any version. I can see the models when I use the getModels.py. I can use importFollow.py but when I run ChaturbateRecorder nothing is found. Does anybody else have this problem? Looking for a solution

**Comment by Qwatuz** [comment]
I found it was because of wrongly installing python/pip. You need to make sure you have the correct version of python and pip.

**Comment by beaston02** [comment]
I haven't been to active on development of these scripts lately as I just haven't had time to put into it. 

On the current version, did you get any error output, or did it just not start recording models?

The getModels.py file is not used in the current version. I changed it to use chaturbates API instead, which is much faster for checking.

**Comment by DeathxBouns** [comment]
@Qwatuz Ok I'll try to upgrade or reinstall pip for python 3.6

@beaston02 On the current version no error output it just starts recording models but says 0 found. On the older version the error output is the one posted.

**Comment by DeathxBouns** [comment]
pi@raspberrypi:~ $ pip3.6 --version
pip 9.0.1 from /usr/local/lib/python3.6/site-packages (python 3.6)
pi@raspberrypi:~ $ python3.6 --version
Python 3.6.0

@Qwatuz Heres my python/pip. Is something off here not a pro at python so feel free to tell me I'm dumb or something.

**Comment by Qwatuz** [comment]
@DeathxBouns you're using 3.6 when it is 3.5 you should be using.

**Comment by Qwatuz** [comment]
Try this on a fresh server install of ubuntu 16.04.


`apt-get update && apt-get upgrade -y && apt-get install python3-pip -y && pip3 install --upgrade pip && apt-get install python3-setuptools && python3.5 -m pip install livestreamer bs4 lxml gevent`

**Comment by DeathxBouns** [comment]
I tried all this in a fresh VM Ubuntu 16.04 still same issue. I even ran a fork version of this that uses streamlink same issue there. Zero models found I don't know. No error message. Path is right. Models one per line. I got nothing

**Comment by Qwatuz** [comment]
@DeathxBouns try a new server with a different IP.

**Comment by DeathxBouns** [comment]
I found a different fork  that worked thanks for all the help @Qwatuz
