### ISSUE TITLE
ImportFollowed  configparser.NoSectionError: No section: 'paths'

### ISSUE THREAD

**Issue by andyrav** [beaston02/ChaturbateRecorder#33]
getting the follwing error when running ImportFollowed.py
like it is not reading the config file.
if hard code the look up variables it works.

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/configparser.py", line 1138, in _unify_values
    sectiondict = self._sections[section]
KeyError: 'paths'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ImportFollowed.py", line 10, in <module>
    wishlist = Config.get('paths', 'wishlist')
  File "/usr/local/lib/python3.6/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/usr/local/lib/python3.6/configparser.py", line 1141, in _unify_values
    raise NoSectionError(section)
configparser.NoSectionError: No section: 'paths'

**Comment by andyrav** [comment]
changed to 
Config.read("config/config.conf")
and works
