### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by chopraaa** [beaston02/ChaturbateRecorder#37]
Worked fine for a while but now it's throwing out of threads and memory errors like this one:

```
Exception in thread Thread-85:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\livestreamer\stream\segmented.py", line 153, in run
    result = future.result(timeout=0.5)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\concurrent\futures\_base.py", line 405, in result
    return self.__get_result()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\livestreamer\stream\hls.py", line 84, in fetch
    **request_params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\livestreamer\plugin\api\http_session.py", line 128, in request
    *args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\sessions.py", line 658, in send
    r.content
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\models.py", line 823, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
MemoryError
```
 Windows with Python 3.6.1.

**Comment by chopraaa** [comment]
Resolved using Python x64. 💯
