### ISSUE TITLE
i am put the name into want.txt ,but not star download

### ISSUE THREAD

**Issue by p1020119** [beaston02/ChaturbateRecorder#43]
λ python C:\ChaturbateRecorder-master\ChaturbateRecorder.py
[2018-02-08 21:18:38] 0 model(s) are being recorded. Getting list of online models now
Traceback (most recent call last):orded: []
  File "C:\ChaturbateRecorder-master\ChaturbateRecorder.py", line 137, in <module>
    getOnlineModels()
  File "C:\ChaturbateRecorder-master\ChaturbateRecorder.py", line 104, in getOnlineModels
    f = open(wishlist, 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/Users/Joe/chaturbate/wanted.txt'

**Comment by mitch619911** [comment]
Dude change your directory to your PC's info.... jesus.

**Comment by mitch619911** [comment]
Read the post...... https://github.com/beaston02/ChaturbateRecorder#requirements

**Comment by p1020119** [comment]
i am mean , i am not use chaturbate.com loin,and use chaturbate.cc loin,can i download?

**Comment by p1020119** [comment]
now the comme info is  λ python ChaturbateRecorder.py
[2018-02-08 23:04:47] 0 model(s) are being recorded. Getting list of online models now
the following models are being recorded: []
it mean is it work ?

**Comment by p1020119** [comment]
i am cant find any videoes ?!!!!!

**Comment by mitch619911** [comment]
0 model(s) are being recorded. Getting list of online models now
the following models are being recorded: []

If it was recording it would look like this:

1 model(s) are being recorded. Getting list of online models now
the following models are being recorded: [model_username]

Your videos are saved in the folder you set them to save in, under your config.conf settings.

**Comment by p1020119** [comment]
yes, i have setting the folder config.conf,but cant find the folder?i just put the name into want .txt ,and setting the folder, it is ok?any more setting ?

**Comment by p1020119** [comment]
[paths]
wishlist =C:\ChaturbateRecorder-master\wanted.txt
save_directory = C:\ChaturbateRecorder-master

**Comment by p1020119** [comment]
why cant be download?

**Comment by mitch619911** [comment]
If your username in wanted.txt is live then it should be recording.

**Comment by p1020119** [comment]
but is was not any vides

**Comment by p1020119** [comment]
i am use the differ link to loin chaturbate, not just chaturbate.com,chaturbate.cc it can be loin

**Comment by p1020119** [comment]
can u fix it what happen?
